spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/doisag
    username: admindoisag
    password: <insiraSenha>
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  server:
    port: 8080